// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xthbpztanmuwgvdtmchq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0aGJwenRhbm11d2d2ZHRtY2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTE2MjgsImV4cCI6MjA2NTc2NzYyOH0.5gCOm6cNN4NvxdKFdrhiyYctXMYzckTgRO54Tkil-H8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);